name:                icd-clean-up
version:             0.1.0.0
github:              "g-plane/icd"
license:             MIT
author:              "Pig Fang"
maintainer:          "g-plane@hotmail.com"
copyright:           "2020-present Pig Fang"
description:         Please see the README on GitHub at <https://github.com/g-plane/icd#readme>
extra-source-files: []

dependencies:
- base >= 4.7 && < 5

executables:
  clean-up-exe:
    main:                Main.hs
    source-dirs:         clean-up
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - directory
