name: AUR

on:
  push:
    paths:
      - PKGBUILD

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish AUR package
        uses: guumaster/aur-publish-docker-action@v1
        with:
          package_name: icd
          commit_username: 'Pig Fang'
          commit_email: g-plane@hotmail.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
